FROM --platform=linux/arm64 ubuntu:20.04

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get install -y python3.8 && \
    ln -s /usr/bin/python3.8 /usr/bin/python && \
    apt-get install -y python3-pip

# Set up python environment #
RUN apt install python3.8-venv
RUN python3 -m venv /cpdb python=3.8
RUN . cpdb/bin/activate

COPY env/requirements_cpdb.txt /tmp/requirements_cpdb.txt
RUN pip3 install --upgrade pip && pip3 install -r /tmp/requirements_cpdb.txt

WORKDIR /
