## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##     GaitiLab/scrnaseq-cellcomm-pipeline 1.1.0dev
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##     This is an example parameter file to pass to the `-params-file` option
##     of nextflow run with the GaitiLab/scrnaseq-cellcomm-pipeline pipeline.
##
##     Uncomment lines with a single '#' if you want to pass the parameter to
##     the pipeline.
## -----------------------------------------------------------------------------
input_file: "test_data/example_data.rds"
annot: "seurat_annotations"
sample_var: "Sample"
