---
title: "Analysis: Number of interactions - Comparison between PT and TC regions (undirected)"
author: "Joan Kant"
params:
    input_file: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/402_aggregation/402c_aggregation_integration.rds"
    # output_dir: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/scRNAseq/CCI_CellClass_L2_2_reassigned_samples"
    output_dir: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/TEST"
    condition_varname: "Region"    
    remove_autocrine: 1
output: html_document
---

```{r, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, out.height = "\\textheight", out.width = "\\textwidth", warning = FALSE, message = FALSE)

library(GaitiLabUtils)
library(GBMutils)
set_wd()

# Set up logging
logr <- init_logging(log_level = 5)

# Load libraries
pacman::p_load(glue, data.table, tidyverse, stringr)
devtools::load_all("./", export_all = FALSE)

# Load additional libraries
pacman::p_load(ggplot2, ggpubr, scales, ggtext, ComplexHeatmap)

# TMP: only temporary for testing (interactively)
# params <- list()
# params$output_dir <- glue("{here::here()}/002_WIP_FIGURES_local/scRNAseq/CCI_CellClass_L2_2_reassigned_samples")
# params$input_file <- "output/CCI_CellClass_L2_2_reassigned_samples/402_aggregation/402c_aggregation_integration.rds"
# params$condition_varname <- "Region"
# params$group1 <- "PT"
# params$group2 <- "TC"
# params$remove_autocrine <- 1

color_group <- GBMutils::load_color_palette("Divergent_1")[["Group2"]]

# log_info("Create output directory...")
create_dir(params$output_dir)
```


```{r}
# Custom for GBM - used for heatmap annotation
celltype_levels <- names(GBMutils::load_color_palette("CCI_CellClass_L2_2"))
malign <- celltype_levels[1:3]
tme_oi <- c("Myeloid_Inflammatory", "Myeloid_Immunosuppressive", "Neuron")
tme_other <- setdiff(celltype_levels, c(malign, tme_oi))
celltype_levels <- c(malign, tme_oi, tme_other)


# log_info("Load data + formatting...")
obj <- readRDS(params$input_file) %>%
    # Additional filtering on p-value (aggregate rank)
    filter(pval < 0.05) %>%
    separate(source_target, c("source", "target"), sep = "__", remove = FALSE) %>%
    # Remove direction by sorting source-target alphabetically
    rowwise() %>%
    mutate(source_target_undirected = paste0(sort(c(source, target)), collapse = "__")) %>%
    # Remove duplicate interactions, when they are found in both directions only keep 1
    distinct(!!sym(params$condition_varname), source_target_undirected, complex_interaction, .keep_all = FALSE) %>%
    separate(source_target_undirected, c("source", "target"), sep = "__") %>%
    mutate(source = factor(source, levels = celltype_levels), target = factor(target, levels = celltype_levels)) %>%
    arrange(!!sym(params$condition_varname), source, target, .by_group = TRUE) %>%
    # Count number of interactions per source-target per region
    group_by(!!sym(params$condition_varname), target, source) %>%
    summarise(n = n()) %>%
    ungroup()
# # A tibble: 6 × 4
#   !!sym(params$condition_varname target                    source                     n
#   <fct>          <chr>                     <chr>                  <int>
# 1 PT             Astrocyte                 Astrocyte                101
# 2 PT             Differentiated_like       Differentiated_like        4
# 3 PT             Invasive-high OPC/NPC1    Astrocyte                 48
# 4 PT             Invasive-high OPC/NPC1    Differentiated_like       23
# 5 PT             Invasive-high OPC/NPC1    Invasive-high OPC/NPC1    83
# 6 PT             Myeloid_Immunosuppressive Astrocyte                 92

# log_info(glue("Convert to wide format based on levels in '{params$condition_varname}'..."))
log_info(glue("Convert to wide format based on levels in '{params$condition_varname}'..."))
obj_wide_condition <- obj %>%
    group_by(!!sym(params$condition_varname)) %>%
    arrange(source, .by_group = TRUE) %>%
    pivot_wider(names_from = target, values_from = n, values_fill = 0, names_sort = TRUE) %>%
    ungroup()
# head(obj_wide_condition)
# # A tibble: 6 × 5
#   source                 target                       PT    TC diff_n
#   <chr>                  <chr>                     <int> <int>  <int>
# 1 Astrocyte              Astrocyte                   101     0    101
# 2 Differentiated_like    Differentiated_like           4    77    -73
# 3 Astrocyte              Invasive-high OPC/NPC1       48     0     48
# 4 Differentiated_like    Invasive-high OPC/NPC1       23    67    -44
# 5 Invasive-high OPC/NPC1 Invasive-high OPC/NPC1       83    67     16
# 6 Astrocyte              Myeloid_Immunosuppressive    92     0     92
log_info("Convert to wide format based on cell type labels with the difference in interactions as values...")
for (region_oi in names(GBMutils::load_color_palette("Region"))) {
    obj_sub <- obj_wide_condition %>%
        filter(!!sym(params$condition_varname) == region_oi) %>%
        select(-!!sym(params$condition_varname)) %>%
        column_to_rownames("source")

    log_info("Convert to matrix...")
    mat <- data.matrix(obj_sub)
    colnames(mat) <- str_replace_all(colnames(mat), "_", "-")
    rownames(mat) <- str_replace_all(rownames(mat), "_", "-")

    log_info("Add missing cell types...")
    missing_celltypes <- setdiff(colnames(mat), rownames(mat))
    to_add <- data.frame(row.names = missing_celltypes, matrix(rep(0, ncol(mat) * length(missing_celltypes)), ncol = ncol(mat)))
    colnames(to_add) <- colnames(mat)

    mat <- rbind(mat, to_add)[colnames(mat), ]

    log_info("Fill whole matrix (mirror)...")
    mat <- mat + t(mat)
    mat[lower.tri(mat)] <- 0

    if (params$remove_autocrine) {
        log_info("Remove autocrine interactions (diagonal)...")
        # Remove diagonal (autocrine)
        diag(mat) <- 0
        # print(mat)
        #                              Astrocyte Differentiated_like Invasive-high OPC/NPC1 Myeloid_Immunosuppressive Myeloid_Inflammatory Neuron OPC Oligodendrocyte Progenitor_like T_cell
        # Astrocyte                         0                   0                     48                        92                   99    141 125              86              36     15
        # Differentiated_like               0                   0                    -44                      -255                  -33     27   0            -131            -108    -15
        # Invasive-high OPC/NPC1            0                   0                      0                       -54                    2    142  42              28             -63     12
        # Myeloid_Immunosuppressive         0                   0                      0                         0                    0     76  62             -62            -194     -1
        # Myeloid_Inflammatory              0                   0                      0                         0                    0     80  63              21             -11     26
        # Neuron                            0                   0                      0                         0                    0      0 151             133             101     14
    } else {
        log_info("Not removing autocrine interactions (diagonal)...")
    }
    log_info("Remove fully empty columns/rows...")
    mat <- mat[, which(colSums(mat) != 0)]
    mat <- mat[which(rowSums(mat) != 0), ]
    mat <- data.matrix(mat)

    # print(mat)
    #                           Invasive-high OPC/NPC1 Myeloid_Immunosuppressive Myeloid_Inflammatory Neuron OPC Oligodendrocyte Progenitor_like T_cell
    # Astrocyte                                     48                        92                   99    141 125              86              36     15
    # Differentiated_like                          -44                      -255                  -33     27   0            -131            -108    -15
    # Invasive-high OPC/NPC1                         0                       -54                    2    142  42              28             -63     12
    # Myeloid_Immunosuppressive                      0                         0                    0     76  62             -62            -194     -1
    # Myeloid_Inflammatory                           0                         0                    0     80  63              21             -11     26
    # Neuron                                         0                         0                    0      0 151             133             101     14
    # OPC                                            0                         0                    0      0   0              84              45     19
    # Oligodendrocyte                                0                         0                    0      0   0               0             -83     10
    # Progenitor_like                                0                         0                    0      0   0               0               0     -6

    split_label_col <- factor(lapply(colnames(mat), function(name) {
        if (name %in% str_replace_all(malign, "_", "-")) {
            return("Tumor")
        } else if (name %in% str_replace_all(tme_oi, "_", "-")) {
            return("TME\nof interest")
        } else {
            return("TME")
        }
    }) %>% unlist(), levels = c("Tumor", "TME\nof interest", "TME"))

    split_label_row <- factor(lapply(rownames(mat), function(name) {
        if (name %in% str_replace_all(malign, "_", "-")) {
            return("Tumor")
        } else if (name %in% str_replace_all(tme_oi, "_", "-")) {
            return("TME\nof interest")
        } else {
            return("TME")
        }
    }) %>% unlist(), levels = c("Tumor", "TME\nof interest", "TME"))


    # Determine min/max values for heatmap
    legend_max <- plyr::round_any(max(mat), 5, f = ceiling)
    legend_min <- plyr::round_any(min(mat), 5, f = floor)

    # Setup colors
    color_fun <- circlize::colorRamp2(c(0, legend_max), c("white", color_group))

    chosen_cell_func <- get_cell_function(matrix = mat, is_upper_tri = TRUE, add_annot = TRUE)
    # With annotation
    log_info("Plot Heatmap and save...")
    hm <- create_hm(
        matrix = mat,
        col = color_fun,
        name = glue("Interactions"),
        cell_fun = chosen_cell_func,
        column_title = "", row_title = "",
        column_title_rot = 0, cluster_rows = FALSE, cluster_columns = FALSE,
        cell_width = 10, cell_height = 10,
        row_split = split_label_row, column_split = split_label_col
    )
    save_hm(hm_obj = hm, output_file = glue("{params$output_dir}/heatmap__{region_oi}__undirected_w_annot.pdf"), )

    # Without annotation
    chosen_cell_func <- get_cell_function(is_upper_tri = TRUE, add_annot = FALSE)

    create_hm(
        matrix = mat,
        col = color_fun,
        name = glue("Interactions"),
        cell_fun = chosen_cell_func,
        column_title = "", row_title = "",
        column_title_rot = 0, cluster_rows = FALSE, cluster_columns = FALSE,
        cell_width = 10, cell_height = 10,
        row_split = split_label_row, column_split = split_label_col
    )
    save_hm(hm_obj = hm, output_file = glue("{params$output_dir}/heatmap__{region_oi}__undirected.pdf"))
}
```

# Session Info
```{r session_info}
options(width = 120)
sessioninfo::session_info()
```