---
title: "Analysis: Ranking interactions for cell type pairs of interest"
author: "Joan Kant"
params:
    input_file: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/402_aggregation/402c_aggregation_integration.rds"
    output_dir: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/scRNAseq/CCI_CellClass_L2_2_reassigned_samples"
    unique_interactions: "/Users/joankant/Library/CloudStorage/OneDrive-UHN/Spatial_GBM/Analysis/WIP/scRNAseq/CCI/CCI_CellClass_L2_2_reassigned_samples_unique_interactions_neuron_invasive_high.xlsx"
    condition_varname: "Region"
    top_n: 10
    condition_oi: "PT"
    source: "Neuron"
    target: "Invasive-high OPC/NPC1"
output: html_document
---

```{r ,echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, out.height = "\\textheight", out.width = "\\textwidth", warning = FALSE, message = FALSE)

# # TODO remove later, just for testing temporary
library(GaitiLabUtils)
library(GBMutils)
set_wd()

# Set up logging
logr <- init_logging(log_level = 5)

# Load **libraries**
pacman::p_load(glue, data.table, tidyverse, stringr)
devtools::load_all("./", export_all = FALSE)

# Load additional libraries
pacman::p_load(ggplot2, ggpubr, scales, ggtext, ComplexHeatmap, ggrepel, readxl)

# TMP: only temporary for testing (interactively)
# params <- list()
# params$input_file <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/402_aggregation/402c_aggregation_integration.rds"
# params$output_dir <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/scRNAseq/CCI_CellClass_L2_2_reassigned_samples"
# params$unique_interactions <- "/Users/joankant/Library/CloudStorage/OneDrive-UHN/Spatial_GBM/Analysis/WIP/scRNAseq/CCI/CCI_CellClass_L2_2_reassigned_samples_unique_interactions_neuron_invasive_high.xlsx"
# params$condition_varname <- "Region"
# params$top_n <- 10
# params$source <- "Neuron"
# params$target <- "Invasive-high OPC/NPC1"
# params$condition_oi <- "PT"

# log_info("Create output directory...")
create_dir(params$output_dir)


# TODO move to txt file
genes_oi <- c("NRXN", "L1CAM")

source_target_oi <- paste0(params$source, "__", params$target)
source_target_oi_rev <- paste0(params$target, "__", params$source)

st_oi_formatted <- str_replace_all(source_target_oi, c("/" = "_", " " = "_"))
st_oi_rev_formatted <- str_replace_all(source_target_oi_rev, c("/" = "_", " " = "_"))

# Load detected intearctions
obj <- readRDS(params$input_file)

all_unique_interactions <- read_excel(params$unique_interactions) %>% mutate(log10p = -log10(pval))
```

## Visualization 
### Labeling interactions based on genes of interest 
```{r}
# Select subset of interactions based on cell type pair
label_by_gene <- function(interactions_df, condition_varname, condition_oi, gene_oi, source_oi, target_oi, is_directed = TRUE) {
    st <- paste0(source_oi, "__", target_oi)
    st_rev <- paste0(target_oi, "__", source_oi)
    st_formatted <- str_replace_all(st, c("/" = "_", " " = "_"))

    if (is_directed) {
        st_vec <- c(st)
    } else {
        st_vec <- c(st, st_rev)
    }
    interactions_of_interest <- interactions_df %>%
        filter(source_target %in% st_vec, !!sym(condition_varname) == condition_oi) %>%
        mutate(log10p = -log10(pval)) %>%
        arrange(desc(log10p), desc(CellChat_score), .by_group = TRUE)

    if (!is_directed) {
        interactions_of_interest <- interactions_of_interest %>%
            # In case of duplicate interactions (interaction identified in both directions), keep only the one with highest log10p + score
            distinct(complex_interaction, .keep_all = TRUE)
    }
    interactions_of_interest <- interactions_of_interest %>%
        # Rank
        mutate(order_id = row_number(), complex_interaction = str_replace_all(complex_interaction, "__", "-"))

    p <- ggplot(data = interactions_of_interest, aes(x = order_id, y = log10p)) +
        geom_point() +
        GBM_theme() +
        labs(y = "-log10(pval)", x = "rank by -log10(pval)", title = glue("{source_oi} - {target_oi}")) +
        geom_label_repel(
            # data = interactions_of_interest %>% filter(str_detect(complex_interaction, gene_oi)) %>% arrange(desc(log10p)) %>% head(10),
            aes(
                label = ifelse(str_detect(complex_interaction, gene_oi),
                    str_replace_all(complex_interaction, "__", "-"), ""
                ),
            ),
            min.segment.length = unit(0.1, "lines"),
        ) +
        theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), strip.text.y.right = element_text(angle = 0, hjust = 0)) +
        scale_y_continuous(breaks = scales::pretty_breaks())
    suffix <- ifelse(is_directed, "directed", "undirected")
    ggsave(plot = p, filename = glue("{params$output_dir}/hockey__{st_formatted}_in_{condition_oi}_label_by_{gene_oi}_interactions_{suffix}.pdf"), width = 12, height = 8)

    return(p)
}

# Select subset of interactions based on cell type pair
label_by_multiple_genes <- function(interactions_df, condition_varname, condition_oi, genes_oi, source_oi, target_oi, is_directed = TRUE) {
    # Define colors
    genes_oi_color <- GBMutils::load_color_palette("General_groups")[-1]
    names(genes_oi_color) <- genes_oi
    st <- paste0(source_oi, "__", target_oi)
    st_rev <- paste0(target_oi, "__", source_oi)

    st_formatted <- str_replace_all(st, c("/" = "_", " " = "_"))

    if (is_directed) {
        st_vec <- c(st)
    } else {
        st_vec <- c(st, st_rev)
    }

    interactions_of_interest <- interactions_df %>%
        filter(source_target == st_vec, !!sym(condition_varname) == condition_oi) %>%
        mutate(log10p = -log10(pval)) %>%
        arrange(desc(log10p), desc(CellChat_score), .by_group = TRUE)

    if (!is_directed) {
        # In case of duplicate interactions (interaction identified in both directions), keep only the one with highest log10p + score
        interactions_of_interest <- interactions_of_interest %>%
            distinct(complex_interaction, .keep_all = TRUE)
    }
    interactions_of_interest <- interactions_of_interest %>%
        # Rank
        mutate(order_id = row_number(), complex_interaction = str_replace_all(complex_interaction, "__", "-"))

    p <- ggplot(data = interactions_of_interest, aes(x = order_id, y = log10p)) +
        geom_point() +
        GBM_theme() +
        labs(y = "-log10(pval)", x = "rank by -log10(pval)", title = glue("{source_oi} - {target_oi}")) +
        geom_label_repel(
            data = interactions_of_interest %>% filter(
                str_detect(complex_interaction, paste0(genes_oi, collapse = "|")), pval < 0.05
            ) %>% rowwise() %>% mutate(group = paste0(genes_oi[lapply(complex_interaction, str_detect, genes_oi) %>% unlist()], collapse = ",")) %>% ungroup(),
            aes(
                label = complex_interaction,
                color = group
            ),
            min.segment.length = unit(0.1, "lines"),
        ) +
        scale_color_manual(values = genes_oi_color) +
        theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), strip.text.y.right = element_text(angle = 0, hjust = 0)) +
        scale_y_continuous(breaks = scales::pretty_breaks())
    suffix <- ifelse(is_directed, "directed", "undirected")

    ggsave(plot = p, filename = glue("{params$output_dir}/hockey__{st_formatted}_in_{condition_oi}_label_by_multi_genes_interactions_{suffix}.pdf"), width = 12, height = 8)

    return(p)
}
# unirected
p <- lapply(genes_oi, label_by_gene, interactions_df = obj, condition_varname = params$condition_varname, condition_oi = params$condition_oi, source_oi = params$source, target_oi = params$target, is_directed = FALSE)
print(p)
p <- label_by_multiple_genes(interactions_df = obj, condition_varname = params$condition_varname, condition_oi = params$condition_oi, genes_oi = genes_oi, source_oi = params$source, target_oi = params$target, is_directed = FALSE)

print(p)

# Directed
p <- lapply(genes_oi, label_by_gene, interactions_df = obj, condition_varname = params$condition_varname, condition_oi = params$condition_oi, source_oi = params$source, target_oi = params$target)
print(p)
p <- label_by_multiple_genes(interactions_df = obj, condition_varname = params$condition_varname, condition_oi = params$condition_oi, genes_oi = genes_oi, source_oi = params$source, target_oi = params$target)
print(p)
```

### Labeling top-N interactions by rank
```{r}
# Select subset of interactions based on cell type pair
label_top_n_ranked <- function(interactions_df, condition_varname, condition_oi, top_n, source_oi, target_oi, is_directed = TRUE) {
    # interactions_df <- obj
    # condition_varname <- params$condition_varname
    # condition_oi <- params$condition_oi
    # top_n <- params$top_n
    # source_oi <- params$source
    # target_oi <- params$target
    # is_directed <- FALSE

    st <- paste0(source_oi, "__", target_oi)
    st_rev <- paste0(target_oi, "__", source_oi)
    st_formatted <- str_replace_all(st, c("/" = "_", " " = "_"))

    if (is_directed) {
        st_vec <- c(st)
    } else {
        st_vec <- c(st, st_rev)
    }
    interactions_of_interest <- interactions_df %>%
        filter(source_target %in% st_vec, !!sym(condition_varname) == condition_oi) %>%
        mutate(log10p = -log10(pval)) %>%
        arrange(desc(log10p), desc(CellChat_score), .by_group = TRUE)

    if (!is_directed) {
        interactions_of_interest <- interactions_of_interest %>%
            # In case of duplicate interactions (interaction identified in both directions), keep only the one with highest log10p + score
            distinct(complex_interaction, .keep_all = TRUE)
    }
    nrow(interactions_of_interest)
    interactions_of_interest <- interactions_of_interest %>%
        # Rank
        mutate(order_id = row_number(), complex_interaction = str_replace_all(complex_interaction, "__", "-"))

    p <- ggplot(data = interactions_of_interest, aes(x = order_id, y = log10p)) +
        geom_point() +
        GBM_theme() +
        labs(y = "-log10(pval)", x = "rank by -log10(pval)", title = glue("{source_oi} - {target_oi}")) +
        geom_label_repel(
            data = interactions_of_interest %>% filter(order_id <= top_n),
            aes(
                label = complex_interaction
            ),
            min.segment.length = unit(0.1, "lines"),
        ) +
        theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), strip.text.y.right = element_text(angle = 0, hjust = 0)) +
        scale_y_continuous(breaks = scales::pretty_breaks())
    suffix <- ifelse(is_directed, "directed", "undirected")
    ggsave(plot = p, filename = glue("{params$output_dir}/hockey__{st_formatted}_in_{condition_oi}_label_top{top_n}_rank_interactions_{suffix}.pdf"), width = 12, height = 8)

    return(p)
}

# Undirected
p <- label_top_n_ranked(interactions_df = obj, condition_varname = params$condition_varname, condition_oi = params$condition_oi, top_n = params$top_n, source_oi = params$source, target_oi = params$target, is_directed = FALSE)
print(p)
# Directed
p <- label_top_n_ranked(interactions_df = obj, condition_varname = params$condition_varname, condition_oi = params$condition_oi, top_n = params$top_n, source_oi = params$source, target_oi = params$target, is_directed = TRUE)
print(p)
```

### Labeling unique interactions
Labeling based on the rank of the unique interactions in the Excel sheet, **NOT** the actual rank when using all interactions for the selected cell type pair and region. 
```{r}
# Select subset of interactions based on cell type pair
label_unique_interactions <- function(interactions_df, unique_interactions_df, condition_varname, condition_oi, source_oi, target_oi, is_directed = TRUE, top_n = NULL) {
    # # TMP
    # interactions_df <- obj
    # unique_interactions_df <- all_unique_interactions
    # condition_varname <- params$condition_varname
    # condition_oi <- params$condition_oi
    # top_n <- NULL
    # source_oi <- params$source
    # target_oi <- params$target
    # is_directed <- FALSE


    st <- paste0(source_oi, "__", target_oi)
    st_rev <- paste0(target_oi, "__", source_oi)
    st_formatted <- str_replace_all(st, c("/" = "_", " " = "_"))

    if (is_directed) {
        st_vec <- c(st)
    } else {
        st_vec <- c(st, st_rev)
    }

    # Grab unique interactions
    unique_interactions_df <- unique_interactions_df %>%
        filter(source_target %in% st_vec, !!sym(condition_varname) == condition_oi) %>%
        mutate(log10p = -log10(pval)) %>%
        arrange(desc(log10p), desc(CellChat_score), .by_group = TRUE) %>%
        distinct(complex_interaction, .keep_all = TRUE) %>%
        # Ranking
        mutate(unique_order_id = min_rank(desc(log10p))) %>%
        select(unique_order_id, complex_interaction, unique_order_id) %>%
        ungroup() %>%
        # Add dummy, used for merging later, and format interaction string for visualization
        mutate(is_unique = TRUE, complex_interaction = str_replace_all(complex_interaction, "__", "-"))



    interactions_of_interest <- interactions_df %>%
        filter(source_target %in% st_vec, !!sym(condition_varname) == condition_oi) %>%
        mutate(log10p = -log10(pval)) %>%
        arrange(desc(log10p), desc(CellChat_score), .by_group = TRUE) %>%
        # In case of duplicate interactions (interaction identified in both directions), keep only the one with highest log10p + score
        distinct(complex_interaction, .keep_all = TRUE) %>%
        # Rank
        mutate(order_id = row_number(), complex_interaction = str_replace_all(complex_interaction, "__", "-"))

    interactions_of_interest_unique_labeled <- interactions_of_interest %>% left_join(unique_interactions_df)

    p <- ggplot(data = interactions_of_interest_unique_labeled, aes(x = order_id, y = log10p)) +
        geom_point() +
        GBM_theme() +
        labs(y = "-log10(pval)", x = "rank by -log10(pval)", title = glue("{source_oi} - {target_oi}")) +
        geom_label_repel(
            # Either label the top-N or label all unique interactions
            data = interactions_of_interest_unique_labeled %>% filter(unique_order_id <= ifelse(is.null(top_n), nrow(unique_interactions_df), top_n), is_unique),
            aes(
                label = complex_interaction
            ),
            min.segment.length = unit(0.1, "lines"),
        ) +
        theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), strip.text.y.right = element_text(angle = 0, hjust = 0)) +
        scale_y_continuous(breaks = scales::pretty_breaks())
    suffix <- ifelse(is_directed, "directed", "undirected")
    top_n <- ifelse(is.null(top_n), "all", paste0("top", top_n))
    ggsave(plot = p, filename = glue("{params$output_dir}/hockey__{st_formatted}_in_{condition_oi}_labeled_{top_n}_unique_interactions_{suffix}.pdf"), width = 12, height = 8)
    return(p)
}

# Top-n unique interactions
# Undirected
p <- label_unique_interactions(interactions_df = obj, unique_interactions_df = all_unique_interactions, condition_varname = params$condition_varname, condition_oi = params$condition_oi, top_n = params$top_n, source_oi = params$source, target_oi = params$target, is_directed = FALSE)
print(p)
# Directed
p <- label_unique_interactions(interactions_df = obj, unique_interactions_df = all_unique_interactions, condition_varname = params$condition_varname, condition_oi = params$condition_oi, top_n = params$top_n, source_oi = params$source, target_oi = params$target, is_directed = TRUE)
print(p)

# All unique interactions
# Undirected
p <- label_unique_interactions(interactions_df = obj, unique_interactions_df = all_unique_interactions, condition_varname = params$condition_varname, condition_oi = params$condition_oi, top_n = NULL, source_oi = params$source, target_oi = params$target, is_directed = FALSE)
print(p)
# Directed
p <- label_unique_interactions(interactions_df = obj, unique_interactions_df = all_unique_interactions, condition_varname = params$condition_varname, condition_oi = params$condition_oi, top_n = NULL, source_oi = params$source, target_oi = params$target, is_directed = TRUE)
print(p)
```

# Session Info
```{r session_info}
options(width = 120)
sessioninfo::session_info()
```