---
title: "Analysis: Correlation analysis CCI x bulkRNAseq"
author: "Joan Kant"
params:
    interactions: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/000_misc_local/unique_interactions.xlsx"
    output_dir: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/corr_CCI_bulk"
    printcode: false
    input_dir: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/corr_analysis_bulk_rnaseq_unique_interactions"
    threshold: .35
output: html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = params$printcode)
```

```{r setup, echo = FALSE}
# TODO remove later, just for testing temporary
# params <- list()
# params$interactions <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/000_misc_local/unique_interactions.xlsx"
# params$output_dir <-  "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/corr_CCI_bulk"
# params$input_dir <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/corr_analysis_bulk_rnaseq_unique_interactions"
# params$threshold <- 0.35
library(GaitiLabUtils)
library(GBMutils)
set_wd()

# Set up logging
logr <- init_logging(log_level = 5)

create_dir(params$output_dir)

# Load libraries
pacman::p_load(glue, data.table, tidyverse, stringr)
devtools::load_all("./", export_all = FALSE)

# Load additional libraries
pacman::p_load(ggplot2, ggpubr, scales, ggtext, readxl)


color_palette <- load_color_palette("ATAC")
names(color_palette) <- str_replace_all(names(color_palette), "Neuronal.OPC.like", "Invasive-high OPC/NPC1")

malignant_states <- c("MES.like", "NPC.like", "OPC.like", "AC.like")
```

```{r filter_interactions}
# Interactions
interactions_subset <- read_excel(params$interactions) %>% arrange(pval) %>% 
    separate(complex_interaction, into = c("ligand_complex", "receptor_complex"), sep = "__")

genes_oi <- interactions_subset %>% pull(ligand_complex, receptor_complex) %>% str_split(., ":") %>% unlist() %>% unique()

# Neuron x Invasive-high OPC/NPC1
neuron_ligands <- interactions_subset %>% filter(startsWith(source_target, "Neuron__")) %>% pull(ligand_complex) %>% str_split(., ":") %>% unlist() %>% unique()
invasive_receptors <-  interactions_subset %>% filter(endsWith(source_target, "Neuronal OPC-like")) %>% pull(receptor_complex) %>% str_split(., ":") %>% unlist() %>% unique()

# Invasive-high OPC/NPC1 x Neuron
invasive_ligands <- interactions_subset %>% filter(startsWith(source_target, "Neuronal OPC-like")) %>% pull(ligand_complex) %>% str_split(., ":") %>% unlist() %>% unique()
neuron_receptors <-  interactions_subset %>% filter(endsWith(source_target, "__Neuron")) %>% pull(receptor_complex) %>% str_split(., ":") %>% unlist() %>% unique()

# Genes acting both as ligand and receptor
invasive_dual <- intersect(invasive_ligands, invasive_receptors)
neuron_dual <- intersect(neuron_ligands, neuron_receptors)

```

# TCGA Cohort
```{r load_tcga}
tcga_corr_res <- readRDS(glue("{params$input_dir}/TCGA_corr_boot_CIBERSORT.rds"))$scalop %>% mutate(pair = str_replace_all(pair, "Neuronal.OPC.like", "Invasive-high OPC/NPC1"), gene = factor(gene)) %>%
        separate(pair, into = c("state", "dummy"), sep = "__", remove = FALSE) %>%
        mutate(state = factor(state, names(color_palette))) 

```


Compute number of common genes TCGA x interactions of interest. 
```{r}
tcga_genes <- tcga_corr_res %>% pull(gene) %>% unique()
print(glue("Genes in common: {length(intersect(tcga_genes, genes_oi))} out of {length(genes_oi)}"))

```

## Invasive-high OPC/NPC1
```{r tcga_invasive, fig.width = 20, fig.height = 8}
res <- tcga_corr_res%>%  rowwise() %>%
        filter(state %in% malignant_states | state == "Invasive-high OPC/NPC1") %>% ungroup()

# Unique ligands
unique_ligands <- setdiff(invasive_ligands,invasive_dual)
unique_ligands_res <- res %>% filter(gene %in% unique_ligands)

# Unique receptors
unique_receptors <- setdiff(invasive_receptors,invasive_dual)
unique_receptors_res <- res %>% filter(gene %in% unique_receptors)

dual_res <- res %>% filter(gene %in% invasive_dual)

p_ligands <- ggplot(data = unique_ligands_res, 
aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand")


p_receptors <- ggplot(data =unique_receptors_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Receptor")

p_dual <- ggplot(data = dual_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand/Receptor")

if(nrow(p_ligands$data) > 0 ) {
    print(p_ligands)
    ggsave(p_ligands, filename = glue("{params$output_dir}/TCGA_Invasive_ligands.pdf"), width = 20, height = 8)
}

if(nrow(p_receptors$data) > 0 ) {
    print(p_receptors)
    ggsave(p_receptors, filename = glue("{params$output_dir}/TCGA_Invasive_receptors.pdf"), width = 20, height = 8)
}

if(nrow(p_dual$data) > 0 ) {
    print(p_dual)
    ggsave(p_dual, filename = glue("{params$output_dir}/TCGA_Invasive_dual.pdf"), width = 20, height = 8)
}
```

## Neuron
```{r tcga_neuron, fig.width = 20, fig.height = 8}
res <- tcga_corr_res%>%  rowwise() %>%
        filter(state == "Neuron") %>% ungroup()

# Unique ligands
unique_ligands <- setdiff(neuron_ligands,neuron_dual)
unique_ligands_res <- res %>% filter(gene %in% unique_ligands)

# Unique receptors
unique_receptors <- setdiff(neuron_receptors,neuron_dual)
unique_receptors_res <- res %>% filter(gene %in% unique_receptors)

dual_res <- res %>% filter(gene %in% neuron_dual)

p_ligands <- ggplot(data = unique_ligands_res, 
aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
    geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 
    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand")


p_receptors <- ggplot(data =unique_receptors_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
    geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 
    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Receptor")

p_dual <- ggplot(data =  dual_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
    geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 
    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand/Receptor")

if(nrow(p_ligands$data) > 0 ) {
    print(p_ligands)
    ggsave(p_ligands, filename = glue("{params$output_dir}/TCGA_Neuron_ligands.pdf"), width = 20, height = 8)
}

if(nrow(p_receptors$data) > 0 ) {
    print(p_receptors)
    ggsave(p_receptors, filename = glue("{params$output_dir}/TCGA_Neuron_receptors.pdf"), width = 20, height = 8)
}

if(nrow(p_dual$data) > 0 ) {
    print(p_dual)
    ggsave(p_dual, filename = glue("{params$output_dir}/TCGA_Neuron_dual.pdf"), width = 20, height = 8)
}

```



# GLASS Cohort
```{r load_glass}
glass_corr_res <- readRDS(glue("{params$input_dir}/GLASS_paired_corr_boot_CIBERSORT.rds"))$scalop %>% mutate(pair = str_replace_all(pair, "Neuronal.OPC.like", "Invasive-high OPC/NPC1"), gene = factor(gene)) %>%
        separate(pair, into = c("state", "dummy"), sep = "__", remove = FALSE) %>%
        mutate(state = factor(state, names(color_palette)), gene = factor(gene), Group = factor(Group, levels = c("Primary", "Recurrent"))) 

```

Compute number of common genes GLASS x interactions of interest. 
```{r}
glass_genes <- glass_corr_res %>% pull(gene) %>% unique()
print(glue("Genes in common: {length(intersect(glass_genes, genes_oi))} out of {length(genes_oi)}"))

```


## Invasive-high OPC/NPC1
```{r glass_invasive, fig.width = 20, fig.height = 8}
res <- glass_corr_res %>%  rowwise() %>%
        filter(state %in% malignant_states | state == "Invasive-high OPC/NPC1")

# Unique ligands
unique_ligands <- setdiff(invasive_ligands,invasive_dual)
unique_ligands_res <- res %>% filter(gene %in% unique_ligands)

# Unique receptors
unique_receptors <- setdiff(invasive_receptors,invasive_dual)
unique_receptors_res <- res %>% filter(gene %in% unique_receptors)

dual_res <- res %>% filter(gene %in% invasive_dual)

p_ligands <- ggplot(data = unique_ligands_res, 
aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand") + 
    facet_wrap(. ~ Group, nrow = 2)


p_receptors <- ggplot(data =unique_receptors_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Receptor") + 
    facet_wrap(. ~ Group, nrow = 2)

p_dual <- ggplot(data = dual_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand/Receptor") + 
    facet_wrap(. ~ Group, nrow = 2)

if(nrow(p_ligands$data) > 0 ) {
    print(p_ligands)
    ggsave(p_ligands, filename = glue("{params$output_dir}/GLASS_Invasive_ligands.pdf"), width = 20, height = 8)
}

if(nrow(p_receptors$data) > 0 ) {
    print(p_receptors)
    ggsave(p_receptors, filename = glue("{params$output_dir}/GLASS_Invasive_receptors.pdf"), width = 20, height = 8)
}

if(nrow(p_dual$data) > 0 ) {
    print(p_dual)
    ggsave(p_dual, filename = glue("{params$output_dir}/GLASS_Invasive_dual.pdf"), width = 20, height = 8)
}

```

## Neuron
```{r glass_neuron, fig.width = 20, fig.height = 8}
res <- glass_corr_res%>%  rowwise() %>%
        filter(state == "Neuron")

# Unique ligands
unique_ligands <- setdiff(neuron_ligands,neuron_dual)
unique_ligands_res <- res %>% filter(gene %in% unique_ligands)

# Unique receptors
unique_receptors <- setdiff(neuron_receptors,neuron_dual)
unique_receptors_res <- res %>% filter(gene %in% unique_receptors)

dual_res <- res %>% filter(gene %in% neuron_dual)

p_ligands <- ggplot(data = unique_ligands_res, 
aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand") + 
        facet_wrap(. ~ Group, nrow = 2)

p_receptors <- ggplot(data =unique_receptors_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Receptor") + 
        facet_wrap(. ~ Group, nrow = 2)


p_dual <- ggplot(data =  dual_res, aes(x = gene, y = corr_mean, fill = state)) +
    geom_bar(
        stat = "identity", color = "black",
        position = "dodge"
    ) +
        geom_hline(yintercept = params$threshold, color = "#D1495BFF", linetype = "dashed") + 

    guides(fill = guide_legend(override.aes = list(size = 7), title = "Label")) +
    geom_errorbar(aes(ymin = corr_mean - corr_se, ymax = corr_mean + corr_se),
        width = .2,
        position = position_dodge(.9)
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) + 
    scale_fill_manual(values = color_palette) +
    GBM_theme() +
    labs(x = "Gene", y = "Correlation", title = "Ligand/Receptor") + 
    facet_wrap(. ~ Group, nrow = 2)

if(nrow(p_ligands$data) > 0 ) {
    print(p_ligands)
    ggsave(p_ligands, filename = glue("{params$output_dir}/GLASS_Neuron_ligands.pdf"), width = 20, height = 8)
}

if(nrow(p_receptors$data) > 0 ) {
    print(p_receptors)
    ggsave(p_receptors, filename = glue("{params$output_dir}/GLASS_Neuron_receptors.pdf"), width = 20, height = 8)
}


if(nrow(p_dual$data) > 0 ) {
    print(p_dual)
    ggsave(p_dual, filename = glue("{params$output_dir}/GLASS_Neuron_dual.pdf"), width = 20, height = 8)
}

```

# Session Information
```{r session_info}

options(width = 120)
sessioninfo::session_info()

```