---
title: "Analysis: Impact of cells"
author: "Joan Kant"
params:
    meta: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/000_data/gbm_regional_study__metadata.rds"
    input_file: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/401_combine_samples/401_samples_interactions_mvoted.rds"
    percentile: 0.90
    annot: "CCI_CellClass_L2_2"
    output_dir: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/scRNAseq/CCI_CellClass_L2_2_reassigned_samples"
    condition_varname: "Region"
    avg_expr: "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/average_expression_and_pseudobulk/average_expression_by_Sample_CCI_CellClass_L2_2.rds"

output: html_document
---

```{r ,echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, out.height = "\\textheight", out.width = "\\textwidth", warning = FALSE, message = FALSE)

# # TODO remove later, just for testing temporary
# params <- list()
# params$meta <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/000_data/gbm_regional_study__metadata.rds"
# params$input_file <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/CCI_CellClass_L2_2_reassigned_samples/401_combine_samples/401_samples_interactions_mvoted.rds"
# params$percentile <- 0.90
# params$annot <- "CCI_CellClass_L2_2"
# params$output_dir <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/002_WIP_FIGURES_local/scRNAseq/CCI_CellClass_L2_2_reassigned_samples"
# params$condition_varname <- "Region"
# params$interactions_db <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/data/interactions_db/ref_db.rds"
# params$avg_expr <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/average_expression_and_pseudobulk/average_expression_by_Sample_CCI_CellClass_L2_2.rds"

library(GaitiLabUtils)
library(GBMutils)
set_wd()

# Set up logging
logr <- init_logging(log_level = 5)

# Load libraries
pacman::p_load(glue, data.table, tidyverse, stringr)
devtools::load_all("./", export_all = FALSE)

# Load additional libraries
pacman::p_load(ggplot2, ggpubr, scales, ggtext)


levels_condition <- names(GBMutils::load_color_palette("Region"))

get_possible_interactions <- function(row, list_of_genes) {
    valid_entries <- row[!is.na(row)]
    sum(valid_entries %in% list_of_genes) == length(valid_entries)
}
```

## Loading data

```{r load_data}
log_info("Load metadata...")
meta <- readRDS(params$meta)

log_info("Load significant interactions per sample...")
interactions <- readRDS(params$input_file) %>% separate(source_target, into = c("source", "target"), sep = "__", remove = FALSE)
```

## Formatting the data
```{r, format_data, echo = TRUE}
# Determine number of cells per cell type per sample
log_info("Determine number of cells per cell type per sample...")
n_cells_per_type <- meta %>%
    group_by(Sample, !!as.symbol(params$annot)) %>%
    count()
print(head(n_cells_per_type))

type_of_voting <- "lenient_voting"
# Determine number of interactions for each sample x source-target pair + add the number of cells they have for that cell type pair
all_n_interactions_by_sample <- interactions %>%
    select(Sample, source_target, source, target, complex_interaction, !!sym(params$condition_varname), !!as.symbol(type_of_voting)) %>%
    distinct() %>%
    filter(!!as.symbol(type_of_voting)) %>%
    group_by(!!sym(params$condition_varname), Sample, source_target, source, target) %>%
    reframe(n_interactions = n()) %>%
    # Add number of cells per cell type for source
    left_join(n_cells_per_type %>% rename(n_cells_source = n), by = c("Sample", "source" = params$annot)) %>%
    # Add number of cells per cell type for target
    left_join(n_cells_per_type %>% rename(n_cells_target = n), by = c("Sample", "target" = params$annot)) %>%
    ungroup() %>%
    mutate(Region = factor(Region, names(GBMutils::load_color_palette("Region"))))

knitr::kable(all_n_interactions_by_sample)
```

## Modeling 
```{r}
model <- all_n_interactions_by_sample %>%
    lm(formula = n_interactions ~ n_cells_source + n_cells_target + n_cells_source * n_cells_target + factor(Region))
print(summary(model))

summary(model)$r.squared
summary(model)$adj.r.squared
```

## Visualize 
Visualize the relationship between number of cells in cell type groups and detected number of interactions. In the scatter plot, every dot represents a sample x cell-type pair (directed) combination.

NOTE: interactions are inferred for each sample, then for each cell-type pair in the sample. 

```{r, visualization, fig.width = 17, fig.height = 10}
legend_max <- plyr::round_any(quantile(all_n_interactions_by_sample %>% pull(n_interactions), params$percentile), 25, f = ceiling)

plt <- ggplot(data = all_n_interactions_by_sample) +
    geom_point(aes(x = n_cells_source, y = n_cells_target, color = n_interactions)) +
    GBM_theme() +
    scale_colour_gradient(
        low = GBMutils::load_color_palette("Divergent_3")[1],
        high = GBMutils::load_color_palette("Divergent_3")[2],
        breaks = seq(0, legend_max, 50),
        # Capped at params$percentile (90%), so these values would be considerd NA, therefore manually setting to max (red)
        na.value = GBMutils::load_color_palette("Divergent_3")[2],
        guide = guide_colourbar(barwidth = 10, ticks = TRUE, barheight = unit(0.5, "lines")), aesthetics = "colour", limits = c(0, legend_max)
    ) +
    labs(
        x = "Number of cells sender (log<sub>10</sub>)", y = "Number of cells receiver (log<sub>10</sub>)",
        title = "Relationship between number of cells and detected number of interactions",
        color = "Number of interactions",
        subtitle = glue("Capped colourbar at {params$percentile * 100}% of interactions overall")
    ) +
    ggh4x::facet_grid2(~Region) +
    scale_x_log10(
        breaks = scales::trans_breaks("log10", function(x) 10^x),
        labels = scales::trans_format("log10", scales::math_format(10^.x))
    ) +
    scale_y_log10(
        breaks = scales::trans_breaks("log10", function(x) 10^x),
        labels = scales::trans_format("log10", scales::math_format(10^.x))
    )
plt
ggsave(plot = plt, filename = glue("{params$output_dir}/SUPP_analysis_impact_cell_abundance__{type_of_voting}.pdf"), width = 10, height = 10)
```



```{r}
# interactions_db <- readRDS(params$interactions_db)

# # Extract ligands/receptors (splitting complexes)
# all_ligands <- interactions_db$ligand_complex %>%
#     str_split("\\:") %>%
#     unlist() %>%
#     unique()
# all_receptors <- interactions_db$receptor_complex %>%
#     str_split("\\:") %>%
#     unlist() %>%
#     unique()
# genes_in_db <- c(all_ligands, all_receptors) %>% unique()
# # Genes labeled as ligand AND receptor
# all_dual <- intersect(all_ligands, all_receptors) %>% unique()

# # Load genes that are captured in our data
# genes_in_mat <- readRDS("/Users/joankant/Desktop/gaitigroup/Users/Joan/scrnaseq-cellcomm/output/average_expression_and_pseudobulk/gbm_regional_study_pseudobulk_by_Sample.rds") %>% rownames()

# ligand_subunits <- paste0("ligand_", seq(5))
# receptor_subunits <- paste0("receptor_", seq(5))

# interactions_split_by_unit <- interactions_db %>%
#     separate(ligand_complex, sep = "\\:", into = ligand_subunits) %>%
#     separate(receptor_complex, sep = "\\:", into = receptor_subunits) %>%
#     select(matches("ligand|receptor"))
# ligand_units <- interactions_split_by_unit %>%
#     select(matches("ligand"))
# receptor_units <- interactions_split_by_unit %>%
#     select(matches("receptor"))

# # Determine which interactions (incl. subunits) can be detected based on the genes included in our matrix
# n_potential_interactions <- sum(apply(interactions_split_by_unit, 1, get_possible_interactions, list_of_genes = genes_in_mat))

# print(glue("Number of interactions that can be captured by genes in our data {round(n_potential_interactions / nrow(interactions_db) * 100, 2)}%"))


# avg_expr <- readRDS(params$avg_expr)
# colnames_split <- str_split(names(colnames(avg_expr)), ":|]", simplify = TRUE)[, c(2, 4)]
# new_colnames <- apply(colnames_split, 1, paste0, collapse = ":")
# colnames(avg_expr) <- new_colnames

# avg_exp_long <- data.frame(avg_expr, check.names = FALSE) %>%
#     rownames_to_column("gene") %>%
#     pivot_longer(names_sep = ":", names_to = c("label", "Sample"), cols = all_of(colnames(avg_expr)), values_to = "avg_expression") %>%
#     mutate(is_nonzero = avg_expression > 0, is_greater_than_ncounts = avg_expression >= params$ncounts)
```



```{r}
# all_n_interactions_by_sample <- interactions %>%
#     select(Sample, source_target, source, target, complex_interaction, !!sym(params$condition_varname), !!sym(type_of_voting)) %>%
#     distinct() %>%
#     filter(!!as.symbol(type_of_voting)) %>%
#     group_by(!!sym(params$condition_varname), Sample, source_target, source, target) %>%
#     reframe(n_interactions = n())

# head(avg_exp_long)


# params$ncounts <- 3
# ngenes_by_cell_type_by_sample <- avg_exp_long %>%
#     group_by(Sample, label) %>%
#     summarise(n_nonzero_genes = sum(is_nonzero), n_greater_than_ncounts_genes = sum(is_greater_than_ncounts))


# celltypes <- names(load_color_palette("CCI_CellClass_L2_2"))
# celltype_pairs <- GaitiLabUtils::generate_pairs(celltypes, remove_self = FALSE, return_undirected = TRUE)

# samples <- avg_exp_long %>%
#     pull(Sample) %>%
#     unique()

# combis <- data.frame(expand.grid(samples, celltype_pairs)) %>%
#     rename(Sample = Var1, pair = Var2) %>%
#     separate(pair, into = c("source", "target"), sep = "__")
# head(combis)

# n_potential_interactions_nonzero <- apply(combis, 1, function(row) {
#     source_genes <- avg_exp_long %>%
#         filter(Sample == row[["Sample"]], label == row[["source"]], is_nonzero) %>%
#         pull(gene)
#     target_genes <- avg_exp_long %>%
#         filter(Sample == row[["Sample"]], label == row[["target"]], is_nonzero) %>%
#         pull(gene)

#     n_potential_full_ligands <- apply(ligand_units, 1, get_possible_interactions, list_of_genes = source_genes)
#     n_potential_full_receptors <- apply(receptor_units, 1, get_possible_interactions, list_of_genes = target_genes)
#     n_possible_interactions_pair <- sum(apply(cbind(n_potential_full_ligands, n_potential_full_receptors), 1, sum) == 2)
#     return(n_possible_interactions_pair)
# })
# combis$n_potential_interactions_nonzero <- n_potential_interactions_nonzero
```


# Session Info
```{r session_info}
sessioninfo::session_info()
```